//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infinity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///cmd /c powershell -Nop -NonI -Nologo -WindowStyle Hidden &quot;Write-Host&quot;
        ///
        ///if not &quot;%1&quot;==&quot;am_admin&quot; (powershell start -verb runas &apos;%0&apos; am_admin &amp; exit /b) 
        ///
        ///
        ///del /s /f /q “%USERPROFILE%\Local Settings\History”*.*
        ///rd /s /q “%USERPROFILE%\Local Settings\History”
        ///md “%USERPROFILE%\Local Settings\History”
        ///del /s /f /q “%USERPROFILE%\Local Settings\Temporary Internet Files”*.*
        ///rd /s /q “%USERPROFILE%\Local Settings\Temporary Internet Files”
        ///md “%USERPROFILE%\Local Settings\Temporary Internet Files”
        ///del [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string All_cleaner {
            get {
                return ResourceManager.GetString("All_cleaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_arrows {
            get {
                object obj = ResourceManager.GetObject("back-arrows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///@echo off
        ///title C.By.ARTHHH
        ///color 0A
        ///cls
        ///
        ///cmd /c powershell -Nop -NonI -Nologo -WindowStyle Hidden &quot;Write-Host&quot;
        ///
        ///if not &quot;%1&quot;==&quot;am_admin&quot; (powershell start -verb runas &apos;%0&apos; am_admin &amp; exit /b) 
        ///
        ///
        ///
        ///
        ///net stop w32time
        ///
        ///w32tm /unregister
        ///
        ///w32tm /register
        ///
        ///net start w32time
        ///
        ///w32tm /resync
        ///
        ///
        ///
        ///exit.
        /// </summary>
        internal static string Clock_restart {
            get {
                return ResourceManager.GetString("Clock_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///
        ///if not &quot;%1&quot;==&quot;am_admin&quot; (powershell start -verb runas &apos;%0&apos; am_admin &amp; exit /b) 
        ///cmd /c powershell -Nop -NonI -Nologo -WindowStyle Hidden &quot;Write-Host&quot;
        ///
        ///
        ///
        ///Reg.exe add &quot;HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection&quot; /v &quot;DisableRealtimeMonitoring&quot; /t REG_DWORD /d &quot;1&quot; /f
        ///
        ///
        ///exit
        ///.
        /// </summary>
        internal static string DefenderDisable {
            get {
                return ResourceManager.GetString("DefenderDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///cmd /c powershell -Nop -NonI -Nologo -WindowStyle Hidden &quot;Write-Host&quot;
        ///
        ///if not &quot;%1&quot;==&quot;am_admin&quot; (powershell start -verb runas &apos;%0&apos; am_admin &amp; exit /b) 
        ///
        ///
        ///
        ///Reg.exe delete &quot;HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection&quot; /v &quot;DisableRealtimeMonitoring&quot; /f
        ///
        ///Reg.exe add &quot;HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection&quot; /f
        ///
        ///
        ///exit
        ///.
        /// </summary>
        internal static string DefenderEnable {
            get {
                return ResourceManager.GetString("DefenderEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fast_forward1 {
            get {
                object obj = ResourceManager.GetObject("fast-forward1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_about_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_about_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_back_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_back_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_ccleaner_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_ccleaner_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_ccleaner_48px {
            get {
                object obj = ResourceManager.GetObject("icons8_ccleaner_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_ccleaner_48px1 {
            get {
                object obj = ResourceManager.GetObject("icons8_ccleaner_48px1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_cd_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_cd_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_delete_folder_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_delete_folder_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_downloading_updates_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_downloading_updates_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_folder_tree_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_folder_tree_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_launch_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_launch_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Logout_Rounded_48px {
            get {
                object obj = ResourceManager.GetObject("icons8_Logout_Rounded_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_microsoft_edge_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_microsoft_edge_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_next_page_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_next_page_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_ok_50px {
            get {
                object obj = ResourceManager.GetObject("icons8_ok_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_refresh_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_refresh_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_registry_editor_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_registry_editor_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_restart_48px {
            get {
                object obj = ResourceManager.GetObject("icons8_restart_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_shutdown_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_shutdown_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_shutdown_48px {
            get {
                object obj = ResourceManager.GetObject("icons8_shutdown_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Software_Installer_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_Software_Installer_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_solve_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_solve_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_trash_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_trash_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_unavailable_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_unavailable_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_windows_10_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_windows_10_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_word_32px {
            get {
                object obj = ResourceManager.GetObject("icons8_word_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap infinity__2_ {
            get {
                object obj = ResourceManager.GetObject("infinity__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon infinity__2_1 {
            get {
                object obj = ResourceManager.GetObject("infinity__2_1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///cmd /c powershell -Nop -NonI -Nologo -WindowStyle Hidden &quot;Write-Host&quot;
        ///
        ///if not &quot;%1&quot;==&quot;am_admin&quot; (powershell start -verb runas &apos;%0&apos; am_admin &amp; exit /b) 
        ///
        ///
        ///del /s /f /q “%USERPROFILE%\Local Settings\History”*.*
        ///rd /s /q “%USERPROFILE%\Local Settings\History”
        ///md “%USERPROFILE%\Local Settings\History”
        ///del /s /f /q “%USERPROFILE%\Local Settings\Temporary Internet Files”*.*
        ///rd /s /q “%USERPROFILE%\Local Settings\Temporary Internet Files”
        ///md “%USERPROFILE%\Local Settings\Temporary Internet Files”
        ///
        ///d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Internet_files_delete {
            get {
                return ResourceManager.GetString("Internet_files_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logout {
            get {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap microsoft__1_ {
            get {
                object obj = ResourceManager.GetObject("microsoft__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///cmd /c powershell -Nop -NonI -Nologo -WindowStyle Hidden &quot;Write-Host&quot;
        ///
        ///if not &quot;%1&quot;==&quot;am_admin&quot; (powershell start -verb runas &apos;%0&apos; am_admin &amp; exit /b) 
        ///
        ///RD /S /Q %SystemDrive%\windows.old
        /// 
        ///del /f /s /q %systemdrive%\*.tmp 
        ///
        ///del /f /s /q %systemdrive%\*._mp 
        ///
        ///del /f /s /q %systemdrive%\*.log 
        ///
        ///del /f /s /q %systemdrive%\*.gid 
        ///
        ///del /f /s /q %systemdrive%\*.chk  
        ///
        ///del /f /s /q %systemdrive%\*.old 
        ///
        ///del /f /s /q %windir%\*.bak 
        ///
        ///
        ///
        ///exit
        ///.
        /// </summary>
        internal static string Needless_Windows_Files__Extensions_tmp__mp_log_chk_old_bak_ {
            get {
                return ResourceManager.GetString("Needless_Windows_Files__Extensions_tmp__mp_log_chk_old_bak_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap popupinfinity {
            get {
                object obj = ResourceManager.GetObject("popupinfinity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///cmd /c powershell -Nop -NonI -Nologo -WindowStyle Hidden &quot;Write-Host&quot;
        ///
        ///if not &quot;%1&quot;==&quot;am_admin&quot; (powershell start -verb runas &apos;%0&apos; am_admin &amp; exit /b) 
        ///
        ///
        ///ipconfig /flushdns
        ///ipconfig /registerdns
        ///ipconfig /release
        ///ipconfig /renew
        ///netsh winsock reset
        ///
        ///
        ///exit
        ///.
        /// </summary>
        internal static string Reset_an_Internet_Connection__Flush_DNS_ {
            get {
                return ResourceManager.GetString("Reset_an_Internet_Connection__Flush_DNS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///cmd /c powershell -Nop -NonI -Nologo -WindowStyle Hidden &quot;Write-Host&quot;
        ///
        ///if not &quot;%1&quot;==&quot;am_admin&quot; (powershell start -verb runas &apos;%0&apos; am_admin &amp; exit /b) 
        ///
        ///rd /s /q %prefetch%
        ///mkdir %prefetch%
        ///rd /s /q c:\windows\prefetch\
        ///mkdir c:\windows\prefetch\
        ///
        ///
        ///rd /s /q %temp%
        ///mkdir %temp%
        ///rd /s /q c:\windows\temp\
        ///mkdir c:\windows\temp\
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///exit
        ///.
        /// </summary>
        internal static string Temporary_Files__Temp_Prefetch_Cache_ {
            get {
                return ResourceManager.GetString("Temporary_Files__Temp_Prefetch_Cache_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upgrade {
            get {
                object obj = ResourceManager.GetObject("upgrade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///cmd /c powershell -Nop -NonI -Nologo -WindowStyle Hidden &quot;Write-Host&quot;
        ///
        ///if not &quot;%1&quot;==&quot;am_admin&quot; (powershell start -verb runas &apos;%0&apos; am_admin &amp; exit /b) 
        ///
        ///attrib -h -r -s %windir%\system32\catroot2
        ///attrib -h -r -s %windir%\system32\catroot2.
        ///net stop wuauserv
        ///net stop cryptSvc
        ///net stop bits
        ///net stop msiserver
        ///Ren C:\Windows\SoftwareDistribution SoftwareDistribution.old
        ///Ren C:\Windows\System32\catroot2 Catroot2.old
        ///net start wuauserv
        ///net start cryptSvc
        ///net start bits
        ///net start msiser [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Windows_System__SoftwareDistribution_old_Catroot2_old_ {
            get {
                return ResourceManager.GetString("Windows_System__SoftwareDistribution_old_Catroot2_old_", resourceCulture);
            }
        }
    }
}
